### ISSUE TITLE
IgcDataChart - Tooltip shows up when a mouse is away from a bubble element

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-webcomponents#1064]
## Description  
For a bubble series, a tooltip shows up even when a mouse is away from a bubble. 
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/7463490/4b2ad524-4bba-4511-94a5-8fa968e80221)

## Steps to reproduce  
1. Run the sample.
2. Move the mouse cursor near any bubble.

## Result  
Tooltip shows up even when a mouse is away from a bubble.
It looks like a tooltip actives not along a circular edge of a bubble but a rectangular edge.

## Expected result  
Tooltip shows up only when a mouse is directly over a bubble.

## Attachments  
[bubble-chart-tooltip-template.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/14291206/bubble-chart-tooltip-template.zip)

**Comment by gmurray81** [comment]
In the end, this is actually expected behavior. The hit testing works with square bounding boxes for the markers. This is because not all the markers are circular, and you can actually use arbitrary changes with `markerTemplate` that are aren’t aware of the geometry for. 
You can have us use the actual shapes of the markers to do the hit testing with:

```ts
series.hitTestMode = SeriesHitTestMode.ColorEncoded;
```

This has some performance cost though since we render a special offscreen canvas to do the hit testing, but can check the actual geometry of the markers.

We could add a new property that makes the series assume that the hit test regions for the markers is circular, but we consider the reported behavior the expected behavior and this would be a feature request.
