### ISSUE TITLE
IgcGrid & IgcSelect - The drop-down list of the IgcSelect appears under the Row Edit Overlay of the IgcGrid

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-webcomponents#1076]
## Description  

When the user implemented and ran a client web app that has the "IgcGrid" which enabled row editing and customized with the cell edit template including the "IgcSelect", the drop-down list of the "IgcSelect" was overlapped by the row edit overlay only if the number of rows of the grid was less than 3. It worked as expected if the number of rows equals or exceeds 3.

## Steps to reproduce  

1. Run the sample app I attached to this issue.
2. The web page will have a grid component with 3 rows.
3. Delete 1 row in that grid component using the action strip.
4. Enter row edit mode by double-clicking any cells.
5. the second column in edit mode shows a selection component.
6. Click the drop-down button of that selection component.

## Result  
The drop-down list of the `IgcSelect` appeared under the Row Edit Overlay of the `IgcGrid`.

## Expected result  
The drop-down list of the `IgcSelect` should always appear in front of the Row Edit Overlay of the `IgcGrid`, whatever the number of rows is.

## Attachments  

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/9cc5dfd1-33ff-4d12-8cc7-cb1e2cc26fe3

[📦c-00235378-wc-app1.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/14369876/c-00235378-wc-app1.zip)

**Comment by damyanpetev** [comment]
Pretty much #1012, except we could consider moving the known limitation to a more general spot and including select/dropdown.

This very specific case could potentially be helped by trying to modify the Row Edit overlay outlet logic, though the overlay can just as well stay in the higher stacking outlet as far as the Angular product is concerned, which makes it even worse for templated `igc-select`, etc.
However, the other conflicts present with stacking context (headers, scrolls) will remain and the only sure solution would be to ensure the dropdowns produced by the Web Components sit in the top layer, which would be achievable once the [Popover API](https://caniuse.com/mdn-api_htmlelement_popover) lands, which seems to be quite close now, seeing it's mainly FF and they have it in Nightly already.

@ChronosSF Perhaps instead of closing this as duplicate, we can turn this issue into a task to try to implement that as soon as it's available in a usable state. IIRC the current Floating UI we're using was middleware based, so perhaps we can integrate popover that way.
