### ISSUE TITLE
Feature Request: Adjust component size via CSS custom properties

### ISSUE THREAD

**Issue by brianlagunas** [IgniteUI/igniteui-webcomponents#115]
What's the point of having a `Size` property on the components? Shouldn't this be handled by the Theme or CSS being applied to the component?  Each theme will require the components to have different heights. A generic "Small, Medium, and Large" values will not be an accurate value for all themes we will support.  I see this `Size` property as being very problematic with using these components.

If any thing the `Size` property should be a custom CSS property that can be controlled by a theme or developer, and not an attribute on the components.

For the bootstrap theme this is our default igbInput (top) vs the default input (bottom)

![image](https://user-images.githubusercontent.com/835562/140575167-0758b741-0cc0-4eb5-92bf-071407d30231.png)

The styling doesn't match at all.

I had to put `Size="SizableComponentSize.Small"` on all the inputs, which not only cluttered the code and it was a real pain in the butt, but they still were 2 pixels taller than the default bootstrap `form-control` style.

**Comment by damyanpetev** [comment]
I'd like to revive this as a discussion because I agree it makes a lot of sense to have a global knob to turn the sizing up/down because going through each component to apply size is a hassle. Yes, you can potentially bind that to a global variable (assuming rendering through some framework like lit) but still that doesn't change the situation too much. What we need is something like our density token in Angular but there's no native DI here.

So, ideally though that'd be part of the theme actually - in this case as Brian suggested through a CSS variable.
And that actually makes a lot more sense that the DI token too for a few reasons:
- It's even easier to use a CSS var to control the entire app or scope as needed
- I believe @simeonoff suggested the possibility of themes to apply different size - so inputs & buttons can match either Material Design or Bootstrap in the respective theme. I actually quite like the idea and that supports size as part of the theme
- Something additional we've noticed is the size/density can be applied to typography as well - https://material.io/design/layout/applying-density.html#typography, which I think could be a neat addition as well and would affect more of the app, including text with applied typography 

The only downside ATM, @simeonoff can confirm, is the inability to use string keyword-based variables - as in `--size: medium` because there's no `if --size == medium` conditional in CSS. Unless there's an alternative, we might need to use a slightly less intuitive numeric representation - likely a scale multiplier where 

I even think we should consider describing this behavior on the Design System level @sdimchevski, including theme defaults and consider applying them across the board (incl. Angular). It'll likely be considered a breaking change for specific themes that will set different defaults, though I think that may be worth it for the end result. 

On the technical side - we can keep the respective programmatic options to set size (global or per-component) for backwards compatibility or just in general, with the only caveat that they'll no longer carry a default value and will delegate that to the theme (and likely start setting the CSS var underneath as well).

// CC @ig-georgeA @radomirchev

**Comment by simeonoff** [comment]
@brianlagunas @damyanpetev We've found a solution to the problem. We'll try to remove the attribute from all components this sprint a replace the sizing of all components using CSS custom properties only.

#### Sample Usage:

```css
igc-avatar {
   --size: var(--ig-size-medium);
}
```
