### ISSUE TITLE
Input of type Search is not using the search icon -> 🔍

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-webcomponents#1335]
### Which component(s) are affected?

Input

### Description

Input of type Search is not using the search icon -> 🔍

### Reproduction

1. Open the sample demos
2. Go to Inputs -> Basic
3. Change the input type to Search
![image](https://github.com/user-attachments/assets/0b9befb0-fa5e-439f-a858-5b2ef5cdb324)

### Workaround

NO

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

4.11.1

### Browser/OS/Node environment

any

**Comment by zdrawku** [comment]
The expectations here are yet to be defined @sdimchevski @ig-georgeA

**Comment by sdimchevski** [comment]
@zdrawku when input type is set to search a search icon should be shown as prefix. @simeonoff

**Comment by rkaraivanov** [comment]
@zdrawku @sdimchevski 

AFAIK none of our input components across the various component packages comes with prefixed/suffixed icons by default, following the default browsers behavior for this input type. If you want this, open feature requests here and in the Angular repository.
This will be a substantial visual/behavioral change, however. After we implement this, we will force any user who have slotted a custom icon in a search input to go and adjust their project since now they will have two.

**Comment by rkaraivanov** [comment]
Closing this. As stated above, there should be a separate feature request here and in the Angular repository for this change.
