### ISSUE TITLE
Combo search input padding

### ISSUE THREAD

**Issue by didimmova** [IgniteUI/igniteui-webcomponents#1495]
### Which component(s) are affected?

Combo

### Description

Combo search input currently has dynamic padding, according to the size. But the input should have 8px block padding and 16px inline padding in all sizes for all themes, except Indigo.

### Reproduction

1. Open Combo Story
2. Inspect paddings in different sizes

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

all

### Browser/OS/Node environment

all

**Comment by simeonoff** [comment]
Since the UI kit does not represent the current state of the requested changes, we need to validate it with the design team first.

**Comment by yradoeva** [comment]
Unfortunately, I realized I made a mistake last week when requesting changes to the search input in the combo in WebC.

Aligned with @sdimchevski and the design team, changes should be implemented in Angular, so that the combo's search input is aligned to what we have in WebC. And since we have only M (default) size in the design kits, we will retain the paddings for now as follows:

Material, Fluent & Bootstrap
S size: 8px 4px
M size: 8px
L size: 8px 16px

**Comment by rkaraivanov** [comment]
@yradoeva @didimmova 
In that case can this issue be closed?

**Comment by didimmova** [comment]
> @yradoeva @didimmova 
> 
> In that case can this issue be closed?
> 
> 

Yes
