### ISSUE TITLE
Date picker component

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-webcomponents#174]
_Estimated Delivery FEB 22

To discuss the options for Time picker and Date Range Picker

- [ ] Research
- [ ] Specification
- [ ] Component and tests implementation
- [ ] API Documentation
- [ ] Design implementation

**Comment by brianlagunas** [comment]
Please do not work on this component until we can meet to discuss. We already have a DatePicker and this will result in two different DatePickers. The current DatePicker has features that would need to be added to the new picker that you would be writing. This is because the version you will be writing will be based off Angular and missing a number of features.

We want to have one date picker, but we need a solid plan to make that happen.

**Comment by kdinev** [comment]
@brianlagunas we won't start any work on this without a specification. We need the item in the backlog, because we plan to have the datepicker utilize the calendar component, which is already in the repository. The base for the component is the design system definition of the datepicker, which means that behavior-wise it needs to comply with that. If, for any reason, a feature conflicts with the design system definition, then we need to evaluate and update the design system based on it.
