### ISSUE TITLE
Why does calendar not fetch/mirror value property from attributes?

### ISSUE THREAD

**Issue by gmurray81** [IgniteUI/igniteui-webcomponents#192]
## Description  

Why does calendar not fetch/mirror value property from attributes like the other components? Seems like you could accept an ISO date? and potentially some sort of separated list of ISO dates.

Problem is that Blazor doesn't make it especially pleasant to send values directly to properties, we'd have to auto-gen some interop to do this. So I'm curious if there may have been another approach to accepting these as attributes. I could turn off the light weight handling of the calendar so that we treat it more like one of the DV components, and I may have to do so if we don't adjust the attribute handling.

Additionally, is there a way we could avoid typing things as: `Date | Date[]` this may seem convenient enough from TS, but at the blazor level basically means I need to shift the type to object. Also, it isn't really super convenient at the TS level either, since you'd need to check if its and array or not when using the getter in order to narrow to the actual type present. Isn't it easier to have two properties? and have which one is respected driven by the selection type etc?

Anyhow, let me know if you are going to adjust this or not. I may have to use the full blazor handling for this component in the meantime...

**Comment by DiyanDimitrov** [comment]
> Why does calendar not fetch/mirror value property from attributes like the other components? Seems like you could accept an ISO date? and potentially some sort of separated list of ISO dates.

We didn't add attribute for the value property mainly because of the Date[] values, but we could change that if we agree on a format for setting single and multiple dates. ISO date format sounds good to me since the standard html date input uses such https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value. For the Date[] we could use comma separated strings or a JSON string array. @rkaraivanov, What do you think?

> Additionally, is there a way we could avoid typing things as: `Date | Date[]` this may seem convenient enough from TS, but at the blazor level basically means I need to shift the type to object.

Unfortunately, it is too late to change that since we have released it and it would be a breaking change. We will try to avoid such property types in the future.

**Comment by rkaraivanov** [comment]
@DiyanDimitrov 
Accepting an ISO date or a comma separated string of ISO dates sounds like a doable enhancement for the calendar.

**Comment by DiyanDimitrov** [comment]
@gmurray81. Since we are going to release version 2.0 of the web components and we will include some breaking changes to the API, we have decided to address this issue as well. I have assigned you for a review of the PR.
