### ISSUE TITLE
Cannot bind radio group to a value

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-webcomponents#315]
## Description  
There is no way to bind radio group component to a value.

## Steps to reproduce  

1. Add radio group.
2. Add three radios, e.g. male, female and other.
3. Add a component property, e.g. gender.
4. Try to bind radio group to the gender property.

## Result  
There is no way to bind the radio group.

## Expected result  
It should be possible to bind radio group to a component's property. Also if the value of any of the radios in the group equals the value of the bound property this radio should be checked.

**Comment by rkaraivanov** [comment]
This is by design. The group is just a container controlling layout and focus/navigation state of the underlying `igc-radio` children.
The value/checked state is handled by the radio components themselves (as with the standard radio input grouped by the same **name** attribute) and it has integration with our ***igc-form**.

I'll label this as a feature request and we will take a look at it in the near future.
