### ISSUE TITLE
IgcGrid cell is missing Update method

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-webcomponents#551]
## Description  
The update method is missing on cell

## Steps to reproduce  

get the cell and try to call Update
ex: var cell = grid.getCellByColumn(2,"FirstName");
      cell,Update("Test");

## Result  
Uncaught TypeError: cell.Update is not a function

## Expected result  
cell can be updated using Update method

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
There is a method `update` (case-sensitive) so the intended snippet works
```ts
const cell = this.grid.getCellByColumn(this.row, this.column);
cell.update(this.value);
this.grid.markForCheck();
```
the only quirk is that since the cell is not proxied like the grid, there's a need to trigger a change detection to see the immediate change. Might need to see if there's something to be done to improve that. Alternatively, just for future reference for everyone, there's an almost equivalent method on the Grid component:
```ts
this.grid.updateCell(this.value, this.row, this.column);
```
This one is properly proxied, minor diff is the row param is the key instead of index.
[Grid Editing_webComponents.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/10448255/Grid.Editing_webComponents.zip)
