### ISSUE TITLE
Input: Label flows outside the width of the component

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#581]
## Description  
Make the label longer than the size of the input.

## Result  
The text overflows the width of the input.

## Expected result  
The text should be contained to the width of the input and truncated.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

![image](https://user-images.githubusercontent.com/4118303/206406978-5cd1dc40-43ee-4cfa-9692-127d12f7ef22.png)

**Comment by desig9stein** [comment]
Isn't this expected behavior? imagine this scenario:
<img width="733" alt="Screenshot 2022-12-08 at 12 24 22" src="https://user-images.githubusercontent.com/21260963/206422785-4bbebdb7-543f-47f8-8c9d-cf8ecc5936b3.png">

I believe we don't want to make the label as big as the input and have an ellipsis even when there is no need for it. The ellipsis must be shown only if the label exceeds the boundaries of the page. Unfortunately, if the label is inside the igc-input this can't be done. The only way to show an ellipsis is if the label has a max-width: 100%  and when the label is inside the input 100% means 100% of the input, not the page.
