### ISSUE TITLE
Actions column template Card component has a wrong html order  

### ISSUE THREAD

**Issue by katherinedragieva** [IgniteUI/igniteui-webcomponents#601]
## Description  
Actions column template Card component has a wrong html order  

## Steps to reproduce  
1. Create an application with a card component and choose Actions column template 
2. Compare it to igx-card

## Result  
The card's html has a wrong order. In webcomponents the order is - title, subtitle, img.  The order should be the following - media(img), title, subtitle

![image](https://user-images.githubusercontent.com/35975071/210737796-7b1bd44f-9940-4f3e-96d6-a294c72c2f45.png)

**Comment by simeonoff** [comment]
I believe you're talking about the card header component. The title says `actions column template`, but the screenshot shows the `igc-card-header` component and its slotted elements. The markup order of the elements in the header component is defined by its template, which is:

```html
<section>
  <slot name="thumbnail"></slot>
</section>
<section>
  <header part="header">
    <slot part="title" name="title"></slot>
    <slot part="subtitle" name="subtitle"></slot>
  </header>
  <slot></slot>
</section>
```

You can pass any valid HTML to be rendered in any of the slots, which are rendered in the shadow DOM in the specified order above. What you're showing in your screenshot is the order of the elements as layed out in the light DOM by the end-user developer.

Now, to the meat of the issue, If you want the card-media to be rendered _before_ the title and subtitle headings, you **must** assign the `igc-card-media` element to the `thumbnail` slot. Not specifying a slot would render the element in the default slot, which is rendered _after_ the headings.

In Igniteui for Angular, the internal markup order works like magic, because the angular template imperatively `selects` the elements by tags and does not require you to specify where in the shadow DOM you want your light DOM elements to appear.

**Comment by katherinedragieva** [comment]
Thanks @simeonoff, will take it from here!
