### ISSUE TITLE
Card actions reverse setting is not working for WC

### ISSUE THREAD

**Issue by katherinedragieva** [IgniteUI/igniteui-webcomponents#617]
## Description  
Card actions in Angular has a property called `reverse`, which changes the positions of the icons and buttons. Currently in WC there isn't a way to revert the position of the icons and buttons in the card actions. Is there a way to add revert in WC?

Icons and button have been reverted  in Angular app in the screenshot. By default the button has to be on the left side of the icons.
![image](https://user-images.githubusercontent.com/35975071/212099224-ddc9b6dd-d9ed-465a-9445-f5b67d47d168.png)

**Comment by simeonoff** [comment]
Since Ignite UI for Web Components uses slots and not imperative template construction (angular via the `select` directive), the control of how the buttons are positioned is left in the hands of the developer. What you want is essentially to switch the slots.

For example, if you have the following:

```html
<igc-card-actions>
  <igc-icon-button slot="start" name="home"></igc-icon-button>
  <igc-button slot="end">Like</igc-button>
  <igc-button slot="end">Learn More</igc-button>
</igc-card-actions>
```

This will render the icon button in the beginning, followed by two text buttons.

To reverse the button order, simply change their slots:

<igc-card-actions>
  <igc-icon-button slot="end" name="home"></igc-icon-button>
  <igc-button slot="start">Like</igc-button>
  <igc-button slot="start">Learn More</igc-button>
</igc-card-actions>

Hope that helps.

**Comment by katherinedragieva** [comment]
Thanks @simeonoff , will take it from here.
