### ISSUE TITLE
Default igc-combo and igc-button sizes differ significantly

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-webcomponents#650]
## Description  
The default size of the combo is much taller than the default `igc-button`.

## Steps to reproduce  

1. Place an `igc-combo` and `igc-button` side-by-side in a vertically aligned container.
2. Notice the size difference

## Result  
`igc-combo` is much taller than `igc-button`

## Expected result  
The input, select, combo, button, etc. should be with the same height.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/216569371-b4a3ec54-d070-493a-a2ff-588d86f6f805.png)

**Comment by sdimchevski** [comment]
I think this is an application scenario. The default size of the combo is taller than the default button, yes. That's by design. In material design in all density levels, input fields are taller than buttons, with a difference of 12dp to 16dp, and that's to ensure more space for user interaction in input fields. For example:
<table border="1" cellpadding="10" cellspacing="0">
  <thead>
    <tr>
      <th>Density</th>
      <th>Button Height</th>
      <th>Input Field Height</th>
      <th>Height Difference</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Compact (Small)</td>
      <td>36dp</td>
      <td>48dp</td>
      <td>+12dp</td>
    </tr>
    <tr>
      <td>Cosy (Medium)</td>
      <td>40dp</td>
      <td>56dp</td>
      <td>+16dp</td>
    </tr>
    <tr>
      <td>Comfortable (Large)</td>
      <td>48dp</td>
      <td>64dp</td>
      <td>+16dp</td>
    </tr>
  </tbody>
</table>

**Comment by kdinev** [comment]
@sdimchevski Just to clarify, in order to align horizontally input and button, the only way to do it with out-of-the-box theming and sizing is with small size input and large size button?
