### ISSUE TITLE
igc-combo grows in width when the clear button appears and shrinks when it disappears

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-webcomponents#651]
## Description  
The width of the `igc-combo` changes when the clear button appears.

## Steps to reproduce  

1. Create an app with a combo with the following definition
```html
<igc-combo ?outlined="${true}" .data="${this.northwindCategories}" value-key="categoryID" display-key="categoryID" ?autoFocusSearch="${true}" class="combo"></igc-combo>
```
```css
.combo {
      height: max-content;
      min-width: min-content;
      flex-shrink: 0;
}
```
2. Select an item
3. Then deselect the item

## Result  
On selecting, the clear button appears and the combo grows.

## Expected result  
On deselecting the clear button disappears and the combo shrinks.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/216629503-4e3de14a-a429-4a64-93cf-fb8874025421.png)
![image](https://user-images.githubusercontent.com/1472513/216629605-59fc35f1-c3ac-419f-af18-f4b8c9ae7500.png)

**Comment by simeonoff** [comment]
As far as I am concerned this is the expected behavior. If the parent element has display type of flex and there's space for the child element to grow, it will grow. In the context of the App Builder, this is exactly what is happening. So to me, it looks like an App Builder issue rather than a styling issue in the combo.

**Comment by kdinev** [comment]
@simeonoff I agree. I tested the combo with a fixed width and the container stays with the same dimensions.
