### ISSUE TITLE
The Navigation drawer always displays the end border when position is relative

### ISSUE THREAD

**Issue by mtsvyatkova** [IgniteUI/igniteui-webcomponents#661]
## Description  
When the position of the navigation drawer is relative it does not respects whether it is pinned on the left side or on the right side  of the other controls. The border-inline-end is always shown. In Angular, the content border is controlled by the position property - start or end even in a pinned state, so when the drawer is displayed on the right side (in left-to-right) only the border-inline-start is shown.

## Result  
See the attached image.

## Expected result  
Consistency with the behavior in Angular.

## Attachments  
![NavDrawerBorder](https://user-images.githubusercontent.com/11231206/217864608-74d3d69d-6610-4d03-851d-85717549bb84.png)

**Comment by desig9stein** [comment]
@mtsvyatkova Both, Angular and Web components have end(right) position available only for none relative(pinned) navdrawer, so I am not sure if this is expected to work.

In web components, there is no `pinned` attribute, only `position`: `start`, `end`, `top`, `bottom`, and `relative`, and since we can't have combinations like end/relative, there is no way to add or remove anything for that combination, in this case, the border. @simeonoff @SisIvanova correct me if I am wrong but I believe this is built that way intentionally.

**Comment by mtsvyatkova** [comment]
I agree that the current implementation was not intended to handle the display of the border in relative(pinned) position when the nav drawer is in the end(right). This came up as an inconsistency between the generated Angular and Web components projects in the App Builder.
Similar concerns about the border had come up when the [relative position](https://github.com/IgniteUI/igniteui-webcomponents/issues/311) was added and later as a missing border in [this issue](https://github.com/IgniteUI/igniteui-webcomponents/issues/345). 
@damyanpetev do you think we should consider any change of the current behavior (and what the change should be)?

**Comment by damyanpetev** [comment]
@mtsvyatkova @desig9stein
Indeed, the border was a minor concern when adding the relative option (as linked above, so no need to quote myself). Since start/end can't auto-magically position the drawer when it's `pinned/relative` it made some sense to make them mutually exclusive to avoid confusion.
The start-positioned drawer is the most common use anyway, or perhaps the only valid one if I'm reading the [Material guidelines](https://m3.material.io/components/navigation-drawer/guidelines#6381123f-4f5e-40a8-9104-85291eba67e4) right and I don't see much else out there. Also the border being inline-end means it'll be correct when the drawer is relative on the right in an actual RTL context, which I think is the more likely use (that the `right/end` option might've been there to support back in the day).

Really can't gauge how important this scenario is, but I'm still leaning to it being somewhat minor. Also, not really hard to move the border if need be:
```css
igc-nav-drawer::part(base) {
    border-inline-start: 1px solid hsla(var(--ig-gray-300), var(--ig-gray-a));
    border-inline-end: none;
}
```
So I think we can keep it as is. 
AFAIK, right/left and pinned are also mutually exclusive in the App Builder, hopefully in the UI Kits as well (would love for someone to confirm) and we might want to keep it that way. As long as this component covers that, I'm okay with the Angular counterpart having more options.
