### ISSUE TITLE
Radio Group cannot be used inside a form

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-webcomponents#699]
## Description  
igc-radio-group cannot be used inside a form control.
I couldn't find any example of using the radio group inside a form and I cannot figure a way having in mind that the only option for setting its' value is using the "Checked" property. 

## Steps to reproduce  

1. Navigate to https://codesandbox.io/s/delicate-cherry-hcefvx?file=/index.html
2. Fill in the inputs
3. Click submit

## Result  
the radio group is undefined
![screenshot](https://user-images.githubusercontent.com/2778393/224710926-f4740a1a-3f14-471a-95d8-8595cab90dad.png)

## Expected result  
Radio group can be used inside a form

**Comment by damyanpetev** [comment]
@dafo Yeah, kinda expected as `name` on the radio-s is required. If anything, surprising you get a value at all - fairly certain a native radio+form will not even pick up a value without a name (instead of `undefined: value`) - that one I'd take as a bug.

This is all following what the native form and form controls do (will eventually _be_ the native form, once we can implement `ElementInternals` for our form controls like the radio). The docs do mention you need name + value for form use, though I guess they leave something to be desired.

As for the group is mostly a visual container as it stands, I guess we could discuss adding value on it as a shortcut to control the radios underneath but perhaps as a separate enhancement.

**Comment by dafo** [comment]
Yes, the radio buttons inside the group must have the same name:
```
<igc-radio-group>
    <igc-radio name="fruit" value="apple">Apple</igc-radio>
    <igc-radio name="fruit" value="banana" checked>Banana</igc-radio>
    <igc-radio name="fruit" value="mango">Mango</igc-radio>
    <igc-radio name="fruit" value="orange">Orange</igc-radio>
</igc-radio-group>
```
I have updated the codesandbox examle.
