### ISSUE TITLE
tree-grid foreign-key is case sensitive.

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-webcomponents#706]
## Description  
Grid has no data

## Steps to reproduce  
run sample linked below:
1. run sample with foreign-key="ParentID". Underling property has to be lowercase.

## Result  
Grid has no data

## Expected result  
Grid loads data

## Attachments  
https://github.com/IgniteUI/igniteui-wc-examples/tree/vnext/samples/grids/tree-grid/cell-selection-mode

**Comment by mddifilippo89** [comment]
This has no effect on if parent-id. The underlying property can be lowercase but if the property is set uppercase its fine.

**Comment by damyanpetev** [comment]
@mddifilippo89 Care to elaborate what the issue is with? The foreign key (much like the primary key, column field, etc) is matching a field in the data items and as such it's quite normal to be case-sensitive.

PS: You might want to use 'permalinks' to a specific version like https://github.com/IgniteUI/igniteui-wc-examples/tree/492a0e678af40d4df9db2a8f2b6748ad704553b9/samples/grids/tree-grid/cell-selection-mode instead of the `vnext` ref which moves for such repro-s. Or a Codesandbox or zip attachment, etc.

Regardless, in this initial version I can see the grid using `foreign-key="ParentID"` but the data using `parentID` properties, which expectedly won't work. And I see almost right after this issue is logged you did update the data source to use capital letter props and those have remained as such.

I did run the sample https://github.com/IgniteUI/igniteui-wc-examples/tree/vnext/samples/grids/tree-grid/cell-selection-mode it the current state ([permalink](https://github.com/IgniteUI/igniteui-wc-examples/tree/fa5fd6bc069b0d2dfaf6c450a198be83a5bd514d/samples/grids/tree-grid/cell-selection-mode)) and with `foreign-key="ParentID"` that matches the data source, it ran just fine. Unless I'm missing something, can I assume there is no issue after all and this can be closed?

**Comment by damyanpetev** [comment]
The sample and doc are already live and working as expected https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/tree-grid/cell-selection
With the above explanation, I don't think there's anything left to address.
