### ISSUE TITLE
Stepper - The content of the steps is not stretching vertically

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-webcomponents#738]
## Description  
The content of the steps can't be set to fill the remaining space of its container.

## Steps to reproduce  

1. Open the following sample where the height of the steps' conents are set to 100% - [here](https://codesandbox.io/s/stepper-steps-content-is-not-stretching-vertically-svr95z).
2. See the result.

## Result  
The content isn't stretching vertically.

## Expected result  
The content should fill the remaining space of its container.

## Attachments  
![image](https://user-images.githubusercontent.com/75325639/232912967-bf4af212-4bda-4bb9-8d00-6c71f878769d.png)

**Comment by viktorkombov** [comment]
@desig9stein, the issue is still reproducible. Only the body of the steps (`part="body`) is stretching vertically, but the div with part "content" (`part="content"`) and the slot "content" (`slot="content`) are still not stretching:

![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/75325639/d35ca8c9-2655-4e7e-8997-ce2f0b716a85)

You can find an example that demonstrates the issue - [here](https://filetransfer.infragistics.com/public.php?service=files&t=bd1afb362c71198dc5292feb556a9ad8).

**Comment by desig9stein** [comment]
@viktorkombov I am writing this to wrap up our conversation from earlier.

If I add `display: flex` to the `part='content'` I am forcing the users to wrap their content in another element in order to prevent their items to become flex children if they don't want that. For me, this is not a good idea.

Example:
Imagine that the user puts a few paragraphs as step content since the paragraph is a block element by default, the user would expect each paragraph to take the full width of the `container` and each paragraph to be on a separate line. If I make the content `display: flex` the paragraphs will go next to each other since they now are flex children. 
<img width="840" alt="Screenshot 2023-06-01 at 13 12 22" src="https://github.com/IgniteUI/igniteui-webcomponents/assets/21260963/face7ba5-51a7-4433-b138-fdb18663994f">

The same will happen if I add `display: flex` and `flex-direction: column`. In that case, if the user puts a few `inline` elements they will behave like they are `block`. My suggestion, if possible, is to add height 100% to the generated div `step-content`.

<img width="840" alt="Screenshot 2023-06-01 at 13 13 26" src="https://github.com/IgniteUI/igniteui-webcomponents/assets/21260963/d118071b-d6a9-4b67-8f97-b6690537c1c2">

**Comment by simeonoff** [comment]
Closing this again, as it seems to be an app-related use case.
