### ISSUE TITLE
Calendar: Picker arrows aren't flipped in RTL mode

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#893]
The picker arrows don't point in the right direction when the calendar is used in RTL mode.

Here's a screenshot:
![Screenshot 2023-08-29 at 9 48 05](https://github.com/IgniteUI/igniteui-webcomponents/assets/4118303/e92ec741-a563-40f6-af07-df87ce45f97a)

**Comment by SisIvanova** [comment]
When the orientation of the calendar is set to vertical, the picker arrows should be rotated at 90deg instead of 180deg. See the difference between the vertical calendar in `ltr` and `rtl` directions. This is how it should be displayed: 

<img width="1038" alt="Screenshot 2023-09-05 at 2 09 02 PM" src="https://github.com/IgniteUI/igniteui-webcomponents/assets/59446295/32458480-8785-4419-97ab-64d5c5d3fb98">

**Comment by rkaraivanov** [comment]
@simeonoff @desig9stein 

After merging #910 and moving the direction context to an ancestor element instead of the story component, the issue is still present. As this is a valid application scenario (setting **dir** on the body/html tag itself) I'm reopening this issue.

Current state in the master branch:
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/20106115/7cd7faf9-d723-4ab6-acd2-5793aa2c3d84)
