### ISSUE TITLE
Radio Group: Radio Buttons are not unchecked when another is checked

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-webcomponents#938]
## Description  
When a radio button is checked, the previously checked button is not unchecked.

version: 4.4.0

## Steps to reproduce  

1. Click on some radio button
2. Click on another button

## Result  
![wc-radio-issue](https://github.com/IgniteUI/igniteui-webcomponents/assets/52423497/84175544-cca7-41ce-9511-16025198c971)

## Expected result  
![wc-radio-expected](https://github.com/IgniteUI/igniteui-webcomponents/assets/52423497/9f776990-29f3-4a28-9d83-39a11d50d556)

Note: The issue is not reproducible in the Storybook

**Comment by rkaraivanov** [comment]
@teodosiah 
Do you have a sample reproducing the issue?

**Comment by teodosiah** [comment]
https://codesandbox.io/s/igc-radio-group-wc-4-4-0-issue-forked-498f39?file=/package.json

**Comment by rkaraivanov** [comment]
I would not consider this a bug per se, since radio groups (not the component) are a set
of radio inputs that share the same **name** attribute ([link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#defining_a_radio_group)).



Here is the updated sample:

[![Edit igc-radio-group-wc-4.4.0-issue (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/igc-radio-group-wc-4-4-0-issue-forked-rskh4l?fontsize=14&hidenavigation=1&theme=dark)

**Comment by teodosiah** [comment]
I will log it in the samples repo
